update: async test workflows, similar to Circle

diff --git a/.github/workflows/pipeline-release-tag.yml b/.github/workflows/pipeline-release-tag.yml
--- a/.github/workflows/pipeline-release-tag.yml
+++ b/.github/workflows/pipeline-release-tag.yml
@@ -18,7 +18,7 @@ permissions:
   contents: write
 
 jobs:
-  release:
+  setup:
     runs-on: ubuntu-latest
 
     outputs:
@@ -38,15 +38,6 @@ jobs:
           fetch-tags: true
           # token: ${{ secrets.repo_PAT }}
 
-      - name: Setup
-        run: |
-          make dev-install
-
-          # NOTE: The user email is {user.id}+{user.login}@users.noreply.github.com.
-          # See users API: https://api.github.com/users/github-actions%5Bbot%5D
-          git config user.name "github-actions[bot]"
-          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
-
       - name: Populate variables
         id: versions
         run: |
@@ -62,10 +53,66 @@ jobs:
           echo "devTag=dev-v$setupVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
           echo "releaseTag=v$setupVersion" | tee -a "$GITHUB_OUTPUT" "$GITHUB_ENV"
 
+  mark-as-success:
+    runs-on: ubuntu-latest
+
+    needs:
+      - setup
+
+    steps:
+      - name: Get commit status
+        run: |
+          response=$(curl -sL\
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/${{ github.repository }}/commits/tags/${{ needs.setup.outputs.devTag }}/status
+          )
+
+          if [[ echo "$response" | jq .state != "success" ]]; then
+            echo "Some checks not passed, cannot release."
+            exit 1
+          fi
+
+      # - run: |
+      #     curl --fail-with-body -X PATCH \
+      #         https://api.supertokens.io/0/driver \
+      #         -H 'Content-Type: application/json' \
+      #         -H 'api-version: 0' \
+      #         -d "{
+      #           \"password\": \"${{ secrets.SUPERTOKENS_API_KEY }}\",
+      #           \"version\":\"${{ needs.setup.outputs.setupVersion }}\",
+      #           \"name\": \"python\",
+      #           \"testPassed\": true
+      #         }"`
+
+  release:
+    runs-on: ubuntu-latest
+
+    needs:
+      - setup
+      - mark-as-success
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ inputs.branch }}
+          fetch-tags: true
+          # token: ${{ secrets.repo_PAT }}
+
+      - name: Setup
+        run: |
+          make dev-install
+
+          # NOTE: The user email is {user.id}+{user.login}@users.noreply.github.com.
+          # See users API: https://api.github.com/users/github-actions%5Bbot%5D
+          git config user.name "github-actions[bot]"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
       - if: ${{ inputs.force == 'false' }}
         name: Check tests passed
         run: |
-          testsPassed=`curl -s -X GET "https://api.supertokens.io/0/driver?password=${{ secrets.SUPERTOKENS_API_KEY }}&version=${{ steps.versions.outputs.setupVersion }}&name=python" -H 'api-version: 0'`
+          testsPassed=`curl -s -X GET "https://api.supertokens.io/0/driver?password=${{ secrets.SUPERTOKENS_API_KEY }}&version=${{ needs.setup.outputs.setupVersion }}&name=python" -H 'api-version: 0'`
 
           if [[ echo $testsPassed | jq .testPassed != "true" ]]
           then
@@ -76,7 +123,7 @@ jobs:
       - if: ${{ inputs.force == 'false' }}
         name: Check if core and frontend released
         run: |
-          canReleaseSafelyResponse=`curl -s -X GET "https://api.supertokens.io/0/driver/release/check?password=${{ secrets.SUPERTOKENS_API_KEY }}&version=${{ steps.versions.outputs.setupVersion }}&name=python" -H 'api-version: 0'`
+          canReleaseSafelyResponse=`curl -s -X GET "https://api.supertokens.io/0/driver/release/check?password=${{ secrets.SUPERTOKENS_API_KEY }}&version=${{ needs.setup.outputs.setupVersion }}&name=python" -H 'api-version: 0'`
 
           if [[ echo $canReleaseSafelyResponse | jq .canRelease != "true" ]]
           then
@@ -88,7 +135,7 @@ jobs:
         run: |
           currentCommit=$(git log --format="%H" -n 1)
           currentTag=`git tag -l --points-at $currentCommit`
-          expectedTag="${{ steps.versions.outputs.devTag }}"
+          expectedTag="${{ needs.setup.outputs.devTag }}"
 
           if [[ $currentTag != $expectedTag ]]
           then
@@ -107,34 +154,25 @@ jobs:
           #     -d "{
           #         \"password\": \"${{ secrets.SUPERTOKENS_RELEASE_API_KEY }}\",
           #         \"name\":\"python\",
-          #         \"version\":\"${{ steps.versions.outputs.setupVersion }}\",
+          #         \"version\":\"${{ needs.setup.outputs.setupVersion }}\",
           #         \"release\": true
           #     }"`
-
-      - name: Build docs
-        run: |
-          make build-docs
-
-      - name: Commit doc changes
-        run: |
-          git add --all
-          git commit --allow-empty -nm "doc: update docs for ${{ steps.versions.outputs.releaseTag }} tag"
-          git push
 
       - name: Create release tag, delete dev tag
         run: |
           # Add new release tag
-          git tag ${{ steps.versions.outputs.releaseTag }}
+          git tag ${{ needs.setup.outputs.releaseTag }}
           git push --tags
 
           # Delete current dev tag
-          git tag --delete ${{ steps.versions.outputs.devTag }}
-          git push --delete origin ${{ steps.versions.outputs.devTag }}
+          git tag --delete ${{ needs.setup.outputs.devTag }}
+          git push --delete origin ${{ needs.setup.outputs.devTag }}
 
 
   merge:
     runs-on: ubuntu-latest
     needs:
+      - setup
       - release
 
     steps:
@@ -157,7 +195,15 @@ jobs:
 
       - name: Check API and merge to master
         run: |
-          # response=`curl -s -X GET "https://api.supertokens.io/0/driver/latest/check?password=${{ secrets.SUPERTOKENS_API_KEY }}&version=${{ steps.versions.outputs.setupVersion }}&name=python" -H 'api-version: 0'`
+          # response=$(curl -s\
+          #   -X GET\
+          #   "https://api.supertokens.io/0/driver/latest/check?\
+          #     password=${{ secrets.SUPERTOKENS_API_KEY }}&\
+          #     version=${{ needs.setup.outputs.setupVersion }}&\
+          #     name=python" \
+          #   -H 'api-version: 0'
+          # )
+          # response=`curl -s -X GET "https://api.supertokens.io/0/driver/latest/check?password=${{ secrets.SUPERTOKENS_API_KEY }}&version=${{ needs.setup.outputs.setupVersion }}&name=python" -H 'api-version: 0'`
           response=true
 
           if [[ $response == "true" ]]
@@ -175,12 +221,13 @@ jobs:
   publish:
     runs-on: ubuntu-latest
     needs:
+      - setup
       - release
 
     steps:
       - uses: actions/checkout@v4
         with:
-          ref: ${{ needs.release.outputs.releaseTag }}
+          ref: ${{ needs.setup.outputs.releaseTag }}
           fetch-tags: true
 
       - run: |
